### PR TITLE
Update for @most/core compatibility

### PR DESCRIPTION
**Pull request by hoichi**
Fix for https://github.com/mostjs-community/last/issues/1

Seems almost done. The only issue I’m having now is that recommended Babel 6 config breaks `rollup-plugin-buba`. Submitted a PR for David: https://github.com/davidchase/rollup-plugin-buba/pull/2

### CODE REVIEW

**Comment by TylorS** [comment]
Once we can get tests passing after that PR gets merged LGTM 👍

**Comment by hoichi** [comment]
Yay, they pass. `.babelrc` is sane again.

**Comment by TylorS** [comment]
Awesome, thank you @hoichi

**Comment by TylorS** [comment]
@hoichi If your NPM username is the same as your Github handle you should have permissions to publish this package on NPM

**Pull request merged**
